import * as cdk from "aws-cdk-lib";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as lambdaNodejs from "aws-cdk-lib/aws-lambda-nodejs";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as sqs from "aws-cdk-lib/aws-sqs";
import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";
import { Construct } from "constructs";
import * as path from "path";
import { PROJECT_NAME } from "../config/environments";
import {
  BaseStackProps,
  getRequiredEnv,
  removalPolicy,
  applyStandardTags,
} from "../config/helpers";

/**
 * ImagePipelineStack
 *
 * Provisions the image processing infrastructure for listing photos:
 *
 *   ┌─────────────────────┐     ┌───────────────────────┐
 *   │  S3 Bucket          │     │  SQS Queue            │
 *   │  (originals +       │◄────│  (processing jobs)    │
 *   │   derived variants) │     │                       │
 *   └────────┬────────────┘     └───────────┬───────────┘
 *            │                              │
 *            │                              ▼
 *            │                  ┌───────────────────────┐
 *            │                  │  Lambda               │
 *            │                  │  (sharp resize/webp)  │
 *            │                  └───────────────────────┘
 *            ▼
 *   ┌─────────────────────┐
 *   │  CloudFront CDN     │
 *   │  (derived images)   │
 *   └─────────────────────┘
 *
 * Design decisions:
 * - S3 bucket uses UUID-based immutable keys, so versioning is disabled.
 * - CloudFront uses Origin Access Control (OAC) to securely access S3.
 * - CloudFront OAC grants read access to the entire bucket (listing photos are public).
 * - The API sends SQS messages explicitly after confirming presigned upload;
 *   there are no S3 event notifications.
 * - Sharp is listed as a nodeModule (not bundled by esbuild) because it has
 *   native bindings that must be installed via npm for the Lambda runtime.
 */
export class ListingImagePipelineStack extends cdk.Stack {
  public readonly imagesBucket: s3.Bucket;
  public readonly distribution: cloudfront.Distribution;
  public readonly imageProcessingQueue: sqs.Queue;
  public readonly imageProcessingDeadLetterQueue: sqs.Queue;
  public readonly imageProcessorFunction: lambdaNodejs.NodejsFunction;

  constructor(scope: Construct, id: string, props: BaseStackProps) {
    super(scope, id, props);

    const { config } = props;

    const baseName = `${PROJECT_NAME}-images-${config.envName}`;

    // -------------------------------------------------------------------------
    // S3 Bucket
    //
    // Stores original uploads and derived (resized/converted) variants.
    // All public access is blocked — reads go through CloudFront OAC, writes
    // go through presigned URLs generated by the API.
    // -------------------------------------------------------------------------
    this.imagesBucket = new s3.Bucket(this, "ImagesBucket", {
      bucketName: `${PROJECT_NAME}-images-${config.envName}`,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      versioned: false,
      removalPolicy: removalPolicy(config),
      autoDeleteObjects: !config.isProduction,
      cors: [
        {
          allowedMethods: [s3.HttpMethods.PUT],
          allowedOrigins: ["*"],
          allowedHeaders: ["*"],
          exposedHeaders: ["ETag"],
        },
      ],
      lifecycleRules: [
        {
          transitions: [
            {
              storageClass: s3.StorageClass.INTELLIGENT_TIERING,
              transitionAfter: cdk.Duration.days(90),
            },
          ],
        },
      ],
    });

    // -------------------------------------------------------------------------
    // CloudFront Distribution
    //
    // Serves derived image variants via Origin Access Control (OAC).
    // Uses an immutable cache policy (max-age 1 year) since derived images
    // are keyed by UUID and never change.
    // -------------------------------------------------------------------------
    const oac = new cloudfront.S3OriginAccessControl(this, "ImagesOac", {
      signing: cloudfront.Signing.SIGV4_NO_OVERRIDE,
    });

    const cachePolicy = new cloudfront.CachePolicy(this, "ImagesCachePolicy", {
      cachePolicyName: `${PROJECT_NAME}-images-immutable-${config.envName}`,
      defaultTtl: cdk.Duration.seconds(31536000),
      maxTtl: cdk.Duration.seconds(31536000),
      minTtl: cdk.Duration.seconds(31536000),
      enableAcceptEncodingGzip: true,
      enableAcceptEncodingBrotli: true,
    });

    this.distribution = new cloudfront.Distribution(this, "ImagesCdn", {
      comment: `${PROJECT_NAME}-images-cdn-${config.envName}`,
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(
          this.imagesBucket,
          { originAccessControl: oac },
        ),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy,
        compress: true,
      },
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
    });

    // Note: S3BucketOrigin.withOriginAccessControl automatically adds a bucket
    // policy granting the CloudFront distribution s3:GetObject on the entire
    // bucket. Originals are not a security concern (they are the same public
    // listing photos, just unoptimised), and the frontend only constructs URLs
    // for derived paths — so a blanket allow is acceptable.

    // -------------------------------------------------------------------------
    // Dead-Letter Queue (DLQ)
    // -------------------------------------------------------------------------
    this.imageProcessingDeadLetterQueue = new sqs.Queue(
      this,
      "ImageProcessingDlq",
      {
        queueName: `${PROJECT_NAME}-image-processing-queue-${config.envName}-dlq`,
        retentionPeriod: cdk.Duration.days(14),
        encryption: sqs.QueueEncryption.SQS_MANAGED,
        removalPolicy: removalPolicy(config),
      },
    );

    // -------------------------------------------------------------------------
    // Image Processing Queue
    //
    // Receives messages from the API after a presigned upload completes.
    // Each message contains the imageId, listingId, and originalKey.
    // -------------------------------------------------------------------------
    this.imageProcessingQueue = new sqs.Queue(this, "ImageProcessingQueue", {
      queueName: `${PROJECT_NAME}-image-processing-queue-${config.envName}`,
      visibilityTimeout: cdk.Duration.minutes(5),
      retentionPeriod: cdk.Duration.days(4),
      receiveMessageWaitTime: cdk.Duration.seconds(20),
      encryption: sqs.QueueEncryption.SQS_MANAGED,
      deadLetterQueue: {
        queue: this.imageProcessingDeadLetterQueue,
        maxReceiveCount: 3,
      },
      removalPolicy: removalPolicy(config),
    });

    // -------------------------------------------------------------------------
    // Image Processor Lambda
    //
    // Consumes messages from the image processing queue, downloads the
    // original image from S3, generates resized WebP variants using Sharp,
    // and uploads derived images back to S3.
    // -------------------------------------------------------------------------
    const sentryLayer = lambda.LayerVersion.fromLayerVersionArn(
      this,
      "SentryLayer",
      getRequiredEnv("SQS_FORWARDER_SENTRY_DSN_LAYER_ARN"),
    );

    this.imageProcessorFunction = new lambdaNodejs.NodejsFunction(
      this,
      "ImageProcessorHandler",
      {
        functionName: `${PROJECT_NAME}-image-processor-${config.envName}`,
        runtime: lambda.Runtime.NODEJS_22_X,
        entry: path.join(
          __dirname,
          "..",
          "lambda",
          "image-processor",
          "handler.ts",
        ),
        handler: "handler",
        timeout: cdk.Duration.minutes(5),
        memorySize: 1536,
        layers: [sentryLayer],
        environment: {
          BUCKET_NAME: this.imagesBucket.bucketName,
          SENTRY_DSN: getRequiredEnv("IMAGE_PROCESSOR_SENTRY_DSN"),
          NODE_ENV: config.envName,
        },
        bundling: {
          minify: true,
          sourceMap: true,
          target: "node22",
          // Sharp has native bindings — install via npm rather than bundling.
          nodeModules: ["sharp"],
          // Sentry is provided via a Lambda layer — do not bundle it.
          externalModules: ["@sentry/aws-serverless"],
        },
      },
    );

    // Grant the Lambda read/write access to the S3 bucket.
    this.imagesBucket.grantReadWrite(this.imageProcessorFunction);

    // Wire the SQS queue as an event source for the Lambda.
    this.imageProcessorFunction.addEventSource(
      new SqsEventSource(this.imageProcessingQueue, {
        batchSize: 1,
      }),
    );

    // -------------------------------------------------------------------------
    // CloudFormation Outputs
    // -------------------------------------------------------------------------
    new cdk.CfnOutput(this, "ImagesBucketName", {
      value: this.imagesBucket.bucketName,
      description: "Name of the images S3 bucket",
      exportName: `${baseName}-bucket-name`,
    });

    new cdk.CfnOutput(this, "ImagesBucketArn", {
      value: this.imagesBucket.bucketArn,
      description: "ARN of the images S3 bucket",
      exportName: `${baseName}-bucket-arn`,
    });

    new cdk.CfnOutput(this, "ImagesCdnDomainName", {
      value: this.distribution.distributionDomainName,
      description:
        "CloudFront distribution domain name for serving derived images",
      exportName: `${baseName}-cdn-domain`,
    });

    new cdk.CfnOutput(this, "ImagesCdnDistributionId", {
      value: this.distribution.distributionId,
      description: "CloudFront distribution ID",
      exportName: `${baseName}-cdn-distribution-id`,
    });

    const queueBaseName = `${PROJECT_NAME}-image-processing-queue-${config.envName}`;

    new cdk.CfnOutput(this, "ImageProcessingQueueUrl", {
      value: this.imageProcessingQueue.queueUrl,
      description:
        "URL of the image processing SQS queue (use this to send messages)",
      exportName: `${queueBaseName}-queue-url`,
    });

    new cdk.CfnOutput(this, "ImageProcessingQueueArn", {
      value: this.imageProcessingQueue.queueArn,
      description:
        "ARN of the image processing SQS queue (use this to grant IAM permissions)",
      exportName: `${queueBaseName}-queue-arn`,
    });

    new cdk.CfnOutput(this, "ImageProcessingDlqUrl", {
      value: this.imageProcessingDeadLetterQueue.queueUrl,
      description:
        "URL of the image processing dead-letter queue (monitor for processing failures)",
      exportName: `${queueBaseName}-dlq-url`,
    });

    new cdk.CfnOutput(this, "ImageProcessingDlqArn", {
      value: this.imageProcessingDeadLetterQueue.queueArn,
      description: "ARN of the image processing dead-letter queue",
      exportName: `${queueBaseName}-dlq-arn`,
    });

    applyStandardTags(this, config, "image-pipeline");
  }
}
