import Container from '@mui/material/Container';
import { MuiProvider } from '@repo/web-components/providers/mui-provider';
import { StorageProvider } from '@repo/web-components/storage/storage-provider';
import { CookieDisclaimerWrapper } from '@repo/web/cookie-disclaimer-wrapper';
import { AuthSessionProvider } from '@repo/web/session-provider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { auth } from './auth';
import { HeaderWrapper } from './components/header-wrapper';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MuiProvider>
          <StorageProvider>
            <AuthSessionProvider session={session}>
              <HeaderWrapper />
              <Container maxWidth="lg">{children}</Container>
              <CookieDisclaimerWrapper />
            </AuthSessionProvider>
          </StorageProvider>
        </MuiProvider>
      </body>
    </html>
  );
}
