services:
  db:
    container_name: skye-hosts-db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      TZ: "UTC"
    ports:
      - "25433:5432"
    networks:
      - nestjs-turbo-network

  pgadmin:
    container_name: skye-hosts-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "18080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: '${DATABASE_ADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${DATABASE_ADMIN_PASSWORD}'
    networks:
      - nestjs-turbo-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  nestjs-turbo-network:
    driver: bridge
