import {
  mdiAccountGroupOutline,
  mdiBabyCarriage,
  mdiBabyFaceOutline,
  mdiBagSuitcase,
  mdiBalcony,
  mdiBathtub,
  mdiBeach,
  mdiBed,
  mdiBedEmpty,
  mdiBedKing,
  mdiBedOutline,
  mdiBicycle,
  mdiBilliards,
  mdiBinoculars,
  mdiBlender,
  mdiBookEducation,
  mdiBookOpenPageVariant,
  mdiBookOpenVariant,
  mdiBottleTonic,
  mdiBottleTonicOutline,
  mdiBottleTonicPlus,
  mdiBottleWine,
  mdiBowl,
  mdiBunkBed,
  mdiCalendarMonth,
  mdiCalendarOutline,
  mdiCancel,
  mdiCctv,
  mdiChairRolling,
  mdiChevronRight,
  mdiCircleOutline,
  mdiClipboardTextOutline,
  mdiCloudOutline,
  mdiCoffee,
  mdiCoffeeMaker,
  mdiContentCut,
  mdiCradle,
  mdiCreditCardOutline,
  mdiCubeOutline,
  mdiCupWater,
  mdiCurtains,
  mdiDesk,
  mdiDeskLamp,
  mdiDishwasher,
  mdiDog,
  mdiDogSide,
  mdiDoor,
  mdiDoorOpen,
  mdiDumbbell,
  mdiEarHearing,
  mdiElevationRise,
  mdiEmoticonHappyOutline,
  mdiEthernet,
  mdiEvStation,
  mdiFan,
  mdiFaucet,
  mdiFence,
  mdiFileDocumentOutline,
  mdiFire,
  mdiFireExtinguisher,
  mdiFireplace,
  mdiFlash,
  mdiFlower,
  mdiFoodDrumstick,
  mdiFoodVariant,
  mdiFridge,
  mdiGlassWine,
  mdiGrass,
  mdiGrill,
  mdiHairDryer,
  mdiHandFrontRight,
  mdiHandWash,
  mdiHanger,
  mdiHeatWave,
  mdiHeatingCoil,
  mdiHelpCircleOutline,
  mdiHomeMapMarker,
  mdiHotTub,
  mdiHumanChild,
  mdiImageFilterHdr,
  mdiInformationOutline,
  mdiIron,
  mdiIronBoard,
  mdiKayaking,
  mdiKettle,
  mdiKeyOutline,
  mdiKeyWireless,
  mdiKnife,
  mdiLamp,
  mdiLock,
  mdiLockOutline,
  mdiLockSmart,
  mdiLocker,
  mdiMapOutline,
  mdiMedicalBag,
  mdiMicrowave,
  mdiMirrorRectangle,
  mdiMoleculeCo,
  mdiMoonWaningCrescent,
  mdiOutdoorLamp,
  mdiPaperRoll,
  mdiParking,
  mdiPaw,
  mdiPawOutline,
  mdiPhoneAlert,
  mdiPiano,
  mdiPier,
  mdiPlayCircle,
  mdiPlusCircleOutline,
  mdiPool,
  mdiPotSteam,
  mdiPower,
  mdiPuzzle,
  mdiRadiator,
  mdiRoadVariant,
  mdiSeat,
  mdiShakerOutline,
  mdiShieldCheckOutline,
  mdiShoeFormal,
  mdiShower,
  mdiShowerHead,
  mdiSilverwareForkKnife,
  mdiSilverwareSpoon,
  mdiSilverwareVariant,
  mdiSki,
  mdiSlide,
  mdiSmokeDetector,
  mdiSmokeDetectorVariant,
  mdiSnowflake,
  mdiSnowflakeThermometer,
  mdiSpeakerBluetooth,
  mdiStairs,
  mdiStove,
  mdiTableChair,
  mdiTableFurniture,
  mdiTablePicnic,
  mdiTea,
  mdiTeddyBear,
  mdiTelescope,
  mdiTelevision,
  mdiTelevisionClassic,
  mdiTerrain,
  mdiToaster,
  mdiToasterOven,
  mdiTrashCanOutline,
  mdiTrayFull,
  mdiTumbleDryer,
  mdiWardrobe,
  mdiWashingMachine,
  mdiWaterBoiler,
  mdiWaterOutline,
  mdiWaves,
  mdiWifi,
  mdiWifiStrength4,
} from '@mdi/js';

// When adding a new icon: add the @mdi/js import above and the kebab-case entry below.
// This map covers amenities, safety devices/considerations, house rules, and checkout instructions.
export const mdiIconMap: Record<string, string> = {
  'account-group-outline': mdiAccountGroupOutline,
  'baby-carriage': mdiBabyCarriage,
  'baby-face-outline': mdiBabyFaceOutline,
  'bag-suitcase': mdiBagSuitcase,
  balcony: mdiBalcony,
  bathtub: mdiBathtub,
  beach: mdiBeach,
  bed: mdiBed,
  'bed-king': mdiBedKing,
  'bed-outline': mdiBedOutline,
  bicycle: mdiBicycle,
  billiards: mdiBilliards,
  binoculars: mdiBinoculars,
  blender: mdiBlender,
  'book-child': mdiBookEducation,
  'book-open-page-variant': mdiBookOpenPageVariant,
  'book-open-variant': mdiBookOpenVariant,
  'bottle-tonic': mdiBottleTonic,
  'bottle-tonic-outline': mdiBottleTonicOutline,
  'bottle-tonic-plus': mdiBottleTonicPlus,
  'bottle-wine': mdiBottleWine,
  bowl: mdiBowl,
  'bunk-bed': mdiBunkBed,
  'calendar-month': mdiCalendarMonth,
  'calendar-outline': mdiCalendarOutline,
  cancel: mdiCancel,
  cctv: mdiCctv,
  'chair-rolling': mdiChairRolling,
  'chevron-right': mdiChevronRight,
  'circle-outline': mdiCircleOutline,
  'clipboard-text-outline': mdiClipboardTextOutline,
  'cloud-outline': mdiCloudOutline,
  coffee: mdiCoffee,
  'coffee-maker': mdiCoffeeMaker,
  'content-cut': mdiContentCut,
  cradle: mdiCradle,
  'credit-card-outline': mdiCreditCardOutline,
  'cube-outline': mdiCubeOutline,
  'cup-water': mdiCupWater,
  curtains: mdiCurtains,
  desk: mdiDesk,
  'desk-lamp': mdiDeskLamp,
  dishwasher: mdiDishwasher,
  dog: mdiDog,
  'dog-side': mdiDogSide,
  door: mdiDoor,
  'door-open': mdiDoorOpen,
  dumbbell: mdiDumbbell,
  'ear-hearing': mdiEarHearing,
  'elevation-rise': mdiElevationRise,
  'emoticon-happy-outline': mdiEmoticonHappyOutline,
  ethernet: mdiEthernet,
  'ev-station': mdiEvStation,
  fan: mdiFan,
  fence: mdiFence,
  'file-document-outline': mdiFileDocumentOutline,
  fire: mdiFire,
  'fire-extinguisher': mdiFireExtinguisher,
  fireplace: mdiFireplace,
  flash: mdiFlash,
  flower: mdiFlower,
  'food-drumstick': mdiFoodDrumstick,
  'food-variant': mdiFoodVariant,
  fridge: mdiFridge,
  'glass-wine': mdiGlassWine,
  grass: mdiGrass,
  grill: mdiGrill,
  'hair-dryer': mdiHairDryer,
  'hand-front-right': mdiHandFrontRight,
  'hand-wash': mdiHandWash,
  hanger: mdiHanger,
  'heat-wave': mdiHeatWave,
  'heating-coil': mdiHeatingCoil,
  'home-map-marker': mdiHomeMapMarker,
  'hot-tub': mdiHotTub,
  'human-child': mdiHumanChild,
  'image-filter-hdr': mdiImageFilterHdr,
  'information-outline': mdiInformationOutline,
  iron: mdiIron,
  'iron-board': mdiIronBoard,
  kayaking: mdiKayaking,
  kettle: mdiKettle,
  'key-outline': mdiKeyOutline,
  'key-wireless': mdiKeyWireless,
  knife: mdiKnife,
  lamp: mdiLamp,
  lock: mdiLock,
  'lock-closed-outline': mdiLockOutline,
  'lock-outline': mdiLockOutline,
  'lock-smart': mdiLockSmart,
  locker: mdiLocker,
  'map-outline': mdiMapOutline,
  'medical-bag': mdiMedicalBag,
  microwave: mdiMicrowave,
  'mirror-rectangle': mdiMirrorRectangle,
  'molecule-co': mdiMoleculeCo,
  'moon-outline': mdiMoonWaningCrescent,
  'moon-waning-crescent': mdiMoonWaningCrescent,
  mountain: mdiTerrain,
  'outdoor-lamp': mdiOutdoorLamp,
  'paper-roll': mdiPaperRoll,
  parking: mdiParking,
  paw: mdiPaw,
  'paw-outline': mdiPawOutline,
  'people-outline': mdiAccountGroupOutline,
  'phone-alert': mdiPhoneAlert,
  piano: mdiPiano,
  pier: mdiPier,
  pillow: mdiBedEmpty,
  'play-circle': mdiPlayCircle,
  'plus-circle-outline': mdiPlusCircleOutline,
  pool: mdiPool,
  'pot-steam': mdiPotSteam,
  'power-outline': mdiPower,
  puzzle: mdiPuzzle,
  radiator: mdiRadiator,
  'road-variant': mdiRoadVariant,
  seat: mdiSeat,
  'shaker-outline': mdiShakerOutline,
  'shield-check-outline': mdiShieldCheckOutline,
  'shoe-formal': mdiShoeFormal,
  shower: mdiShower,
  'shower-head': mdiShowerHead,
  'silverware-fork-knife': mdiSilverwareForkKnife,
  'silverware-spoon': mdiSilverwareSpoon,
  'silverware-variant': mdiSilverwareVariant,
  sink: mdiFaucet,
  ski: mdiSki,
  slide: mdiSlide,
  'smoke-detector': mdiSmokeDetector,
  'smoke-detector-variant': mdiSmokeDetectorVariant,
  'ban-outline': mdiCancel,
  snowflake: mdiSnowflake,
  'snowflake-thermometer': mdiSnowflakeThermometer,
  'speaker-bluetooth': mdiSpeakerBluetooth,
  stairs: mdiStairs,
  stove: mdiStove,
  'table-chair': mdiTableChair,
  'table-furniture': mdiTableFurniture,
  'table-picnic': mdiTablePicnic,
  tea: mdiTea,
  'teddy-bear': mdiTeddyBear,
  telescope: mdiTelescope,
  television: mdiTelevision,
  'television-classic': mdiTelevisionClassic,
  toaster: mdiToaster,
  'toaster-oven': mdiToasterOven,
  'towel-rail': mdiRadiator,
  'trash-outline': mdiTrashCanOutline,
  'tray-full': mdiTrayFull,
  'tumble-dryer': mdiTumbleDryer,
  wardrobe: mdiWardrobe,
  'washing-machine': mdiWashingMachine,
  'water-boiler': mdiWaterBoiler,
  'water-outline': mdiWaterOutline,
  'document-text-outline': mdiFileDocumentOutline,
  'happy-outline': mdiEmoticonHappyOutline,
  'add-circle-outline': mdiPlusCircleOutline,
  waves: mdiWaves,
  wifi: mdiWifi,
  'wifi-strength-4': mdiWifiStrength4,
};

/** @deprecated Use mdiIconMap instead */
export const mdiAmenityIconMap = mdiIconMap;

export const mdiFallbackIcon = mdiHelpCircleOutline;
