name: Deploy Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  HEROKU_APP_NAME: skye-hosts-production

jobs:
  # Commenting out because gating is done via husky, if you want to re-introduce, requires Environments.CI added
  # build-and-test: 
  #   name: Build and test
  #   env:
  #     SKYE_ENVIRONMENT: ci
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./
  #   strategy:
  #     matrix:
  #       node-version: [24.13.1]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Cache turbo build setup
  #       uses: actions/cache@v4
  #       with:
  #         path: .turbo
  #         key: ${{ runner.os }}-turbo-${{ github.sha }}
  #         restore-keys: |
  #           ${{ runner.os }}-turbo-
  #
  #     - name: Install Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #
  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         run_install: false
  #
  #     - name: Get pnpm store directory
  #       shell: bash
  #       run: |
  #         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
  #
  #     - uses: actions/cache@v4
  #       name: Setup pnpm cache
  #       with:
  #         path: ${{ env.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-
  #
  #     - name: Install dependencies
  #       run: pnpm install
  #
  #     - name: Lint code
  #       run: pnpm lint
  #
  #     - name: Build (API + shared packages only, frontend built by Vercel)  #Possibly not idea but required for @repo/common to be available during test
  #       run: pnpm turbo run build --filter=skye-hosts-api... --filter=@repo/common...
  #
  #     - name: Tests (Unit)
  #       run: pnpm test
  #
  #     - name: Install Playwright browsers
  #       run: pnpm --filter=skye-hosts-app exec playwright install --with-deps chromium
  #
  #     - name: Tests (e2e)
  #       run: pnpm test:e2e

  deploy-infrastructure-prod:
    name: Deploy AWS Infrastructure (prod)
    # needs: build-and-test
    uses: ./.github/workflows/_deploy-aws-infrastructure.yml
    with:
      env: production #Needed to access Github environment secrets
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BOOKINGS_SQS_FORWARDER_SENTRY_DSN:  ${{ vars.BOOKINGS_SQS_FORWARDER_SENTRY_DSN }}
      CDK_DEPLOY_ACCOUNT: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
      IMAGE_PROCESSOR_SENTRY_DSN: ${{ vars.IMAGE_PROCESSOR_SENTRY_DSN }}
      SCHEDULED_MESSAGES_SQS_FORWARDER_SENTRY_DSN:  ${{ vars.SCHEDULED_MESSAGES_SQS_FORWARDER_SENTRY_DSN }}
      SQS_FORWARDER_HEADER_NAME: ${{ vars.SQS_FORWARDER_HEADER_NAME }}
      SQS_FORWARDER_HTTP_SECRET: ${{ secrets.SQS_FORWARDER_HTTP_SECRET }}
      SQS_FORWARDER_SENTRY_DSN_LAYER_ARN:  ${{ vars.SQS_FORWARDER_SENTRY_DSN_LAYER_ARN }}

  deploy-skye-hosts-api:
    name: Deploy API to Heroku
    needs: deploy-infrastructure-prod
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build --provenance=false -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web -f apps/skye-hosts-api/Dockerfile .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: Derive release version
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${TAG#*-}" >> $GITHUB_ENV

      - name: Set config + Release on Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

          # Set environment variables
          heroku config:set \
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            GITHUB_RUN_NUMBER=${{ github.run_number }} \
            GIT_COMMIT=${{ github.sha }} \
            GIT_REF=${{ github.ref }} \
            RELEASE_VERSION=${{ env.RELEASE_VERSION }} \
            --app $HEROKU_APP_NAME

          # Release container
          heroku container:release web --app $HEROKU_APP_NAME

          heroku ps:scale web=1 --app ${{ env.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}

  deploy-skye-hosts-guest-website:
    name: Deploy Skye Hosts Guest Website
    needs: deploy-skye-hosts-api
    uses: ./.github/workflows/_deploy-vercel-app.yml
    with:
      app-name: skye-hosts-guest-website
      watch-paths: ./apps/skye-hosts-guest-website ./packages/ui ./packages/config ./packages/auth ./packages/theme
      vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
      vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_SKYE_HOSTS_GUEST }}
      env: production
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}

  deploy-skye-glamping-website:
    name: Deploy Skye Glamping Website
    needs: deploy-skye-hosts-api
    uses: ./.github/workflows/_deploy-vercel-app.yml
    with:
      app-name: skye-glamping
      watch-paths: ./apps/skye-glamping-website ./packages/ui ./packages/config ./packages/auth ./packages/theme
      vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
      vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_SKYE_GLAMPING }}
      env: production
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}

  # deploy-skye-hosts-admin-website:
  #   name: Deploy Skye Hosts Admin Website
  #   needs: deploy-skye-hosts-api
  #   uses: ./.github/workflows/_deploy-vercel-app.yml
  #   with:
  #     app-name: skye-hosts-admin-website
  #     watch-paths: ./apps/skye-hosts-admin-website ./packages/ui ./packages/config ./packages/auth
  #     vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
  #     vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_SKYE_HOSTS_ADMIN }}
  #     env: production
  #   secrets:
  #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
